export const REGISTRY_SUCCESS = 'REGISTRY_SUCCESS';
export const REGISTRY_ERROR = 'REGISTRY_ERROR';
export const CLEAN_ALERT = 'CLEAN_ALERT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOGOUT = 'LOGOUT';